const CON = {
  REGISTRATION_START: 'REGISTRATION_START',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILURE: 'REGISTRATION_FAILURE',
  AUTHORIZATION_START: 'AUTHORIZATION_START',
  AUTHORIZATION_SUCCESS: 'AUTHORIZATION_SUCCESS',
  AUTHORIZATION_FAILURE: 'AUTHORIZATION_FAILURE',
  SET_USER_DATA: 'SET_USER_DATA',
  ADD_BLOCK: 'ADD_BLOCK',
  ADD_LINK: 'ADD_LINK',
  DEL_LINK: 'DEL_LINK',
  DEL_BLOCK: 'DEL_BLOCK',
  MOVE_COLUMN: 'MOVE_COLUMN',
  MOVE_LINK_INSIDE_COLUMN: 'MOVE_LINK_INSIDE_COLUMN',
  START_MOVE_LINK_BETWEEN_COLUMNS: 'START_MOVE_LINK_BETWEEN_COLUMNS',
  FINISH_MOVE_LINK_BETWEEN_COLUMNS: 'FINISH_MOVE_LINK_BETWEEN_COLUMNS',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_MODAL_SHOW: 'SIGN_MODAL_SHOW',
  SIGN_MODAL_HIDE: 'SIGN_MODAL_HIDE',
  TRIM_ERROR_MESSAGE: 'TRIM_ERROR_MESSAGE',
  HIDE_PICS: 'HIDE_PICS', 
}

export default CON
